apiVersion: v2
name: incore
icon: https://incore.ncsa.illinois.edu/public/resilience-logo.png
home: https://incore.ncsa.illinois.edu/
description: Run your scientific analyses that model the impact of natural hazards on a community and the resilience of those communities.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.19.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 4.6.0

# List of people that maintain this helm chart.
maintainers:
  - name: Rob Kooper
    email: kooper@illinois.edu
  - name: Yong Wook Kim
    email: ywkim@illinois.edu

# location of source code
sources:
  - https://github.com/IN-CORE

# dependencies for the helm chart, use helm dep install to the install them.
dependencies:
  - name: keycloak
    version: ~18
    repository: https://codecentric.github.io/helm-charts
  - name: postgresql
    version: ~10
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - name: mongodb
    version: ~9
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - name: datawolf
    version: ~1
    repository: https://opensource.ncsa.illinois.edu/charts

# annotations for artifact.io
annotations:
  artifacthub.io/links: |
    - name: Helm Chart
      url: https://github.com/IN-CORE/incore-helm
  artifacthub.io/changes: |
    - Geoserver updated to 2.23.1
    - Jupyterhub seperated from INCORE charts, leveraging of official jupyterhub chart.
