---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: incore-geoserver-pv
  labels:
    name: incore-geoserver
spec:
  storageClassName: manual
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /radiant/projects/bbdk/incore-tst/geoserver
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: incore-data-pv
  labels:
    name: incore-data
spec:
  storageClassName: manual
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /radiant/projects/bbdk/incore-tst/data
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: incore-datawolf-pv
  labels:
    name: incore-datawolf
spec:
  storageClassName: manual
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /radiant/projects/bbdk/incore-tst/datawolf
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      name: incore-geoserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      name: incore-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datawolf-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      name: incore-datawolf
