# Default values for jupyterhub part of INCORE.
# This is a YAML-formatted file.
# Declare variables to be passed into jupyter helm chart.

# ----------------------------------------------------------------------
# JUPYTERHUB
# ----------------------------------------------------------------------
jupyterhub:
  hub:
    image:
      name: hub.ncsa.illinois.edu/incore/hub
      tag: testing
      pullSecrets:
        - regcred
    baseUrl: /hub/
    extraEnv:
      JUPYTER_ENABLE_LAB: "1"
      KEYCLOAK_AUDIENCE: INCORE
      KEYCLOAK_HOSTNAME: incore.example.com
      KEYCLOAK_REALM: In-core
      AUTH_GROUP: incore_user
      AUTH_ROLE: incore_user
    extraConfig:
      incoreConfig.py: |
        from customauthenticator.custom import CustomTokenAuthenticator
        c.Spawner.cmd = ['start.sh', 'jupyterhub-singleuser', '--allow-root']
        c.KubeSpawner.args = ['--allow-root']
        c.JupyterHub.authenticator_class = CustomTokenAuthenticator
        c.CustomTokenAuthenticator.keycloak_url = "https://%s/auth/realms/%s/" % (os.getenv('KEYCLOAK_HOSTNAME'), os.getenv('KEYCLOAK_REALM'))
        c.CustomTokenAuthenticator.auth_cookie_header= "Authorization"
        c.CustomTokenAuthenticator.auth_username_key= "preferred_username"
        c.CustomTokenAuthenticator.auth_uid_number_key = "uid_number"
        c.CustomTokenAuthenticator.enable_auth_state = True
        c.CustomTokenAuthenticator.auto_login = True
        c.CustomTokenAuthenticator.auth_group = os.getenv('AUTH_GROUP')
        c.CustomTokenAuthenticator.auth_role = os.getenv('AUTH_ROLE')
        c.CustomTokenAuthenticator.landing_page_login_url = "https://" + os.getenv('KEYCLOAK_HOSTNAME')
    extraVolumes:
      - name: incore
        configMap:
          name: incore
          defaultMode: 420
    extraVolumeMounts:
      - name: incore
        mountPath: /etc/quota.json
        subPath: quota.json
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    defaultUrl: "/lab"
    image:
      name: hub.ncsa.illinois.edu/incore/lab
      tag: testing
      pullSecrets:
        - regcred
      command4: ["echo", "SUCCESS"]
    # need root to allow to change
    uid: 0
    fsGid: 0
    # mount to user home directorys
    storage:
      homeMountPath: /home/{username}
    extraEnv:
      CHOWN_HOME: 'yes'
      INCORE_SERVER: incore.ncsa.illinois.edu
    #storage:
    #  type: dynamic
    #  capacity: 2Gi
    #  requests: 1Gi
    #  limit: 2Gi
    #  dynamic:
    #    storageClass: nfs-client
  ingress:
    enabled: true
    hosts:
      - incore.example.com