apiVersion: v1
kind: Service
metadata:
  name: {{ include "incore.fullname" . }}-svc-project
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "incore.name" . }}-svc-project
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.svc_project.service.type }}
  ports:
    - port: {{ .Values.svc_project.service.port }}
      name: svc-project
      targetPort: {{ .Values.svc_project.service.port }}
      protocol: TCP
