apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-approval
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.approval.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-approval
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-approval
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.approval.image.pullSecrets | default .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: approval
          image: "{{ .Values.image.project }}/{{ .Values.approval.image.repository }}:{{ .Values.approval.image.tag }}"
          imagePullPolicy: {{ .Values.approval.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: ADMIN_LIST
              value: "jonglee1@illinois.edu,cmnavarr@illinois.edu"
            - name: KEYCLOAK_USERNAME
              value: "keycloak"
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.approval.KEYCLOAK_PASSWORD | default .Values.keycloak.auth.adminPassword | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.approval.KEYCLOAK_URL | default .Values.keycloak.auth.url | default (printf
                "https://%s/auth/" (first .Values.keycloak.ingress.rules).host) | quote }}
            - name: APPROVE_APP_URL
              value: {{ .Values.approval.APPROVE_APP_URL | default .Values.keycloak.auth.approveAppUrl | default (printf "https://%s/approval/approve" (first .Values.keycloak.ingress.rules).host) | quote }}
            - name: EMAIL_FROM
              value: "no-reply@illinois.edu"
            - name: SMTP_SERVER
              value: "outbound-relays.techservices.illinois.edu"
            - name: SMTP_PORT
              value: "25"
          ports:
            - containerPort: {{ .Values.approval.service.port }}
              name: approval
          livenessProbe:
            httpGet:
              path: /approval/healthz
              port: approval
          readinessProbe:
            httpGet:
              path: /approval/healthz
              port: approval
          resources:
            {{- toYaml .Values.approval.resources | nindent 12 }}
      {{- with .Values.approval.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.approval.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.approval.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
