apiVersion: v1
kind: Service
metadata:
  name: {{ include "incore.fullname" . }}-approval
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "incore.name" . }}-approval
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.approval.service.type }}
  ports:
    - port: {{ .Values.approval.service.port }}
      name: approval
      targetPort: {{ .Values.approval.service.port }}
      protocol: TCP
