apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-svc-sema
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-svc-sema
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-svc-sema
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: incore-semantics-jetty
          image: "{{ .Values.image.project }}/{{ .Values.svc_sema.image.repository }}:{{ .Values.svc_sema.image.tag }}"
          env:
            - name: JETTY_PORT
              value: {{ .Values.svc_sema.service.port | quote }}
            - name: SERVICES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SERVICES_URL
            - name: SEMANTICS_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SEMANTICS_MONGODB_URI
            - name: DFR3_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DFR3_MONGODB_URI
            - name: HAZARD_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: HAZARD_MONGODB_URI
            - name: SPACE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SPACE_MONGODB_URI
            - name: DATA_REPO_DATA_DIR
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DATA_REPO_DATA_DIR
            - name: GEOSERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_URL
            - name: GEOSERVER_WORKSPACE
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_WORKSPACE
            - name: GEOSERVER_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_USER
            - name: GEOSERVER_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_PW
            - name: GEOSERVER_ENABLE
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_ENABLE
          ports:
            - containerPort: {{ .Values.svc_sema.service.port }}
              name: svc-sema
          # livenessProbe:
          #   httpGet:
          #     #path: /semantics/api/status
          #     path: /
          #     port: svc-sema
          # readinessProbe:
          #   httpGet:
          #     #path: /semantics/api/status
          #     path: /
          #     port: svc-sema
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
