{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "incore.fullname" . -}}
  {{- $svcPort := .Values.svc_sema.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-svc-sema
  labels:
    {{- include "incore.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://{{ $fullName }}-auth.{{ .Release.Namesema }}.svc.cluster.local:5000/semantics/
    ingress.kubernetes.io/auth-trust-headers: "true"
    ingress.kubernetes.io/auth-response-headers: x-auth-userinfo, X-Auth-Userinfo
    {{- with .Values.svc_sema.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /semantics/
            backend:
              serviceName: {{ $fullName }}-svc-sema
              servicePort: {{ $svcPort }}
    {{- end }}
  {{- end }}
