apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "incore.fullname" . }}-maestro-usersync
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: usergroups-sync
              image: "{{ .Values.image.project }}/{{ .Values.maestro_usersync.image.repository }}:{{ .Values.maestro_usersync.image.tag }}"
              imagePullPolicy: IfNotPresent
              command: ["python"]
              args:
                - "/src/maestro-usersync/sync_users_role_steps_playbook.py"
              env:
                - name: PYTHONUNBUFFERED
                  value: {{ .Values.maestro_usersync.env.PYTHONUNBUFFERED | quote }}
                - name: REALM
                  value: {{ .Values.maestro_usersync.env.REALM | quote }}
                - name: SERVER_BASE_URL
                  value: {{ .Values.maestro_usersync.env.SERVER_BASE_URL | quote }}
                - name: TOKEN_URL
                  value: {{ .Values.maestro_usersync.env.TOKEN_URL | quote }}
                - name: TOKEN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: { { include "incore.fullname" . } }-maestro-usersync
                      key: TOKEN_PASSWORD
                - name: TOKEN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: { { include "incore.fullname" . } }-maestro-usersync
                      key: TOKEN_PASSWORD
                - name: ADMIN_USERNAME
                  value: {{ .Values.maestro_usersync.env.ADMIN_USERNAME | quote }}
                - name: ADMIN_PASSWORD
                  value: {{ .Values.maestro_usersync.env.ADMIN_PASSWORD | quote }}
                - name: SLC_GROUP_ID
                  value: {{ .Values.maestro_usersync.env.SLC_GROUP_ID | quote }}
                - name: JOPLIN_GROUP_ID
                  value: {{ .Values.maestro_usersync.env.JOPLIN_GROUP_ID | quote }}
                - name: GALVESTON_GROUP_ID
                  value: {{ .Values.maestro_usersync.env.GALVESTON_GROUP_ID | quote }}
                - name: NCSA_DEVELOPER_LIST
                  value: {{ .Values.maestro_usersync.env.NCSA_DEVELOPER_LIST | quote }}
                - name: FIRST_RUN
                  value: {{ .Values.maestro_usersync.env.FIRST_RUN | quote }}
          restartPolicy: Never
