apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-svc-maestro
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.svc_maestro.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-svc-maestro
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-svc-maestro
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: incore-maestro
          image: "{{ .Values.image.project }}/{{ .Values.svc_maestro.image.repository }}:{{ .Values.svc_maestro.image.tag }}"
          imagePullPolicy: {{ .Values.svc_maestro.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_SERVER
              value: {{ .Values.svc_maestro.env.host | quote }}
            - name: POSTGRES_PORT
              value: { { .Values.svc_maestro.env.port | quote } }
            - name: POSTGRES_USER
              value: { { .Values.svc_maestro.env.user | quote } }
            - name: POSTGRES_PASSWORD
              value: { { .Values.svc_maestro.env.password | quote } }
            - name: POSTGRES_DB
              value: { { .Values.svc_maestro.env.db_name | quote } }
            - name: ROUTER_PREFIX
              value: { { .Values.svc_maestro.env.prefix | quote } }
            - name: WORKERS
              value: { { .Values.svc_maestro.env.prefix | quote } }
          ports:
            - containerPort: {{ .Values.svc_maestro.service.port }}
              name: svc-maestro
          livenessProbe:
            httpGet:
              path: /maestro
              port: svc-maestro
          readinessProbe:
            httpGet:
              path: /maestro
              port: svc-maestro
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
