{{- if .Values.svc_maestro }}
{{- $fullname := include "incore.fullname" . }}
{{- $labels := include "incore.labels" . }}
{{- range $key, $val := .Values.svc_maestro }}
{{- if or .enabled (not (hasKey . "enabled")) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-svc-maestro-{{ $key }}
  labels:
    {{ $labels | nindent 4 }}
    svc-maestro: {{ $key | quote }}
spec:
  replicas: {{ default 1 .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}-svc-maestro-{{ $key }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $fullname }}-svc-maestro-{{ $key }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: svc-maestro-{{ $key }}
          image: "{{ $.Values.image.project }}/{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy | default $.Values.image.pullPolicy }}
          env:
            - name: POSTGRES_SERVER
              value: {{ .env.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .env.port | quote }}
            - name: POSTGRES_USER
              value: {{ .env.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .env.password | quote }}
            - name: POSTGRES_DB
              value: {{ .env.db_name | quote }}
            - name: ROUTER_PREFIX
              value: {{ .env.prefix | quote }}
            - name: WORKERS
              value: {{ .env.workers | quote }}
          ports:
            - containerPort: {{ .service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /maestro/{{ $key }}/alive
              port: http
          readinessProbe:
            httpGet:
              path: /maestro/{{ $key }}/alive
              port: http
          resources:
            {{- toYaml $.resources | nindent 12 }}
      {{- with $.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}