{{- if .Values.svc_maestro }}
{{- $fullname := include "incore.fullname" . }}
{{- $labels := include "incore.labels" . }}
{{- range $key, $val := .Values.svc_maestro }}
{{- if or .enabled (not (hasKey . "enabled")) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-svc-maestro-{{ $key }}
  labels:
    {{ $labels | nindent 4 }}
    playbook: {{ $key | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ $fullname }}-svc-maestro-{{ $key }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  type: {{ .service.type | default $.Values.service.type }}
  ports:
    - port: {{ .service.port | default $.Values.service.port }}
      name: svc-maestro-{{ $key }}
      targetPort: http
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
