{{- if .Values.playbooks }}
{{- $fullname := include "incore.fullname" . }}
{{- $labels := include "incore.labels" . }}
{{- range $key, $val := .Values.playbooks }}
{{- if or .enabled (not (hasKey . "enabled")) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-playbook-{{ $key }}
  labels:
    {{ $labels | nindent 4 }}
    playbook: {{ $key | quote }}
spec:
  replicas: {{ default 1 .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}-playbook-{{ $key }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $fullname }}-playbook-{{ $key }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: playbook-{{ $key }}
          image: "{{ $.Values.image.project }}/{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy | default $.Values.image.pullPolicy }}
          volumeMounts:
            - name: configs
              mountPath: /usr/share/nginx/html/playbook/{{ $key }}/public
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /playbook/{{ $key }}/
              port: http
          readinessProbe:
            httpGet:
              path: /playbook/{{ $key }}/
              port: http
          resources:
            {{- toYaml $.resources | nindent 12 }}
      volumes:
          - name: configs
            configMap:
              name: {{ $fullname }}-playbook-{{ $key }}
              items:
                - key: asset.config.json
                  path: asset.config.json
                - key: cgeInfo.json
                  path: cgeInfo.json
                - key: datawolf.config.json
                  path: datawolf.config.json
                - key: datawolfWorkflow.config.json
                  path: datawolfWorkflow.config.json
                - key: globals.config.json
                  path: globals.config.json
                - key: hhsInfo.json
                  path: hhsInfo.json
                - key: map.config.json
                  path: map.config.json
      {{- with $.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}