kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "incore.name" . }}-svc-data
  labels:
  {{- include "incore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.svc_data.persistence.size | quote }}
{{- if .Values.frontend.persistence.storageClass }}
  storageClassName: {{ .Values.svc_data.persistence.storageClass }}
{{- end }}
