{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "incore.fullname" . -}}
  {{- $svcPort := .Values.svc_hazard.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-svc-hazard
  labels:
    {{- include "incore.labels" . | nindent 4 }}
  annotations:
    {{- include "incore.authIngressAnnotation" . | nindent 4 }}
    {{- with .Values.svc_hazard.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /hazard/
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-svc-hazard
                port:
                  number: {{ $svcPort }}
    {{- end }}
  {{- end }}
