apiVersion: v1
kind: Service
metadata:
  name: {{ include "incore.fullname" . }}-doc-pyincore-data
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "incore.name" . }}-doc-pyincore-data
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.doc_pyincore_data.service.type }}
  ports:
    - port: {{ .Values.doc_pyincore_data.service.port }}
      name: doc-pyincore
      targetPort: http
      protocol: TCP
