apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incore.name" . }}
data:
  quota.json: |
    {{- .Values.quota | nindent 4 }}
  ga_key.json: |
    "GA-KEY": {{- .Values.google_analytics }}