---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-services
  labels:
    {{- include "incore.labels" . | nindent 4 }}
data:
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
  MAESTRO_USER_PASSWORD: {{ .Values.svc_maestro.password | b64enc | quote }}
  DATA_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "datadb" | b64enc | quote }}
  DFR3_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "dfr3db" | b64enc | quote }}
  HAZARD_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "hazarddb" | b64enc | quote }}
  SPACE_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "spacedb" | b64enc | quote }}
  PROJECT_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "projectdb" | b64enc | quote }}
  SEMANTICS_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "semanticsdb" | b64enc | quote }}
  MAESTRO_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "maestrodb" | b64enc | quote }}
  COMMON_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "commondb" | b64enc | quote }}
  MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "" | b64enc | quote }}
  GEOSERVER_PW: {{ .Values.geoserver.password | b64enc | quote }}
  GEOSERVER_USER: {{ .Values.geoserver.username | b64enc | quote }}
  SERVICES_URL: {{ printf "http://%s-svc-data:%.f" (include "incore.fullname" .) .Values.svc_data.service.port | b64enc | quote }}
  DATA_SERVICE_URL: {{ printf "http://%s-svc-data:%.f" (include "incore.fullname" .) .Values.svc_data.service.port | b64enc | quote }}
  HAZARD_SERVICE_URL: {{ printf "http://%s-svc-hazard:%.f" (include "incore.fullname" .) .Values.svc_hazard.service.port | b64enc | quote }}
  DFR3_SERVICE_URL: {{ printf "http://%s-svc-dfr3:%.f" (include "incore.fullname" .) .Values.svc_dfr3.service.port | b64enc | quote }}
  SPACE_SERVICE_URL: {{ printf "http://%s-svc-space:%.f" (include "incore.fullname" .) .Values.svc_space.service.port | b64enc | quote }}
  PROJECT_SERVICE_URL: {{ printf "http://%s-svc-project:%.f" (include "incore.fullname" .) .Values.svc_project.service.port | b64enc | quote }}
  SEMANTICS_SERVICE_URL: {{ printf "http://%s-svc-sema:%.f" (include "incore.fullname" .) .Values.svc_sema.service.port | b64enc | quote }}
  INFLUXDB_V2_TOKEN: {{ .Values.auth.influxdb.token | b64enc | quote }}
  {{- if .Values.svc_maestro }}
  {{- range $key, $val := .Values.svc_maestro.testbeds }}
  MAESTRO_{{ $key }}_DB_PW: {{ .env.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- if not .Values.datawolf.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-datawolf-postgresql
  labels:
    {{- include "incore.labels" . | nindent 4 }}
type: generic
data:
  postgresql-password: {{ .Values.datawolf.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
