{{- if .Values.keycloak.realmsecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-realm-secret
  labels:
    {{- include "incore.labels" . | nindent 4 }}
type: generic
data:
  "realm.json": {{ .Files.Get .Values.keycloak.realmsecret | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-services
  labels:
    {{- include "incore.labels" . | nindent 4 }}
data:
  DATA_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "datadb" | b64enc | quote }}
  DFR3_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "dfr3db" | b64enc | quote }}
  HAZARD_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "hazarddb" | b64enc | quote }}
  SPACE_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "spacedb" | b64enc | quote }}
  SEMANTICS_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "semanticsdb" | b64enc | quote }}
  MAESTRO_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "maestrodb" | b64enc | quote }}
  COMMON_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "commondb" | b64enc | quote }}
  MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "" | b64enc | quote }}
  GEOSERVER_PW: {{ .Values.geoserver.password | b64enc | quote }}
  GEOSERVER_USER: {{ .Values.geoserver.username | b64enc | quote }}
  SERVICES_URL: {{ printf "http://%s-svc-data:%.f" (include "incore.fullname" .) .Values.svc_data.service.port | b64enc | quote }}
  DATA_SERVICE_URL: {{ printf "http://%s-svc-data:%.f" (include "incore.fullname" .) .Values.svc_data.service.port | b64enc | quote }}
  HAZARD_SERVICE_URL: {{ printf "http://%s-svc-hazard:%.f" (include "incore.fullname" .) .Values.svc_hazard.service.port | b64enc | quote }}
  DFR3_SERVICE_URL: {{ printf "http://%s-svc-dfr3:%.f" (include "incore.fullname" .) .Values.svc_dfr3.service.port | b64enc | quote }}
  SPACE_SERVICE_URL: {{ printf "http://%s-svc-space:%.f" (include "incore.fullname" .) .Values.svc_space.service.port | b64enc | quote }}
  SEMANTICS_SERVICE_URL: {{ printf "http://%s-svc-sema:%.f" (include "incore.fullname" .) .Values.svc_sema.service.port | b64enc | quote }}
  AUTH_LDAP_URL: {{ .Values.ldap.url | b64enc | quote }}
  AUTH_LDAP_USERDN: {{ .Values.ldap.userdn | b64enc | quote }}
  AUTH_LDAP_ADMINS: {{ .Values.ldap.admins | b64enc | quote }}
  AUTH_LDAP_CACHE_REFRESH_SECS: {{ .Values.ldap.refresh | b64enc | quote }}
  AUTH_LDAP_VIEW_ALL: {{ .Values.ldap.viewall | b64enc | quote }}
  INFLUXDB_V2_TOKEN: {{ .Values.auth.influxdb.token | b64enc | quote }}
  {{- if .Values.svc_maestro }}
  {{- range $key, $val := .Values.svc_maestro.testbeds }}
  MAESTRO_{{ $key }}_DB_PW: {{ .env.password | b64enc | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-datawolf
  labels:
    {{- include "incore.labels" . | nindent 4 }}
type: generic
data:
  DATAWOLF_USER: {{ .Values.datawolf.env.db_user | b64enc | quote }}
  DATAWOLF_PASSWORD: {{ .Values.datawolf.env.db_password | b64enc | quote }}
