apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-svc-data
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.svc_data.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-svc-data
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-svc-data
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: incore-data-jetty
          image: "{{ .Values.image.project }}/{{ .Values.svc_data.image.repository }}:{{ .Values.svc_data.image.tag }}"
          imagePullPolicy: {{ .Values.svc_data.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: JETTY_PORT
              value: {{ .Values.svc_data.service.port | quote }}
            - name: DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DATA_MONGODB_URI
            - name: SPACE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SPACE_MONGODB_URI
            - name: COMMON_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: COMMON_MONGODB_URI
            - name: DATA_REPO_DATA_DIR
              value: /home/incore/data
            - name: GEOSERVER_URL
              value: {{ .Values.geoserver.url | quote }}
            - name: GEOSERVER_WORKSPACE
              value: {{ .Values.geoserver.workspace | quote }}
            - name: GEOSERVER_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_USER
            - name: GEOSERVER_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: GEOSERVER_PW
            - name: GEOSERVER_ENABLE
              value: {{ .Values.svc_data.geoserver.enabled | quote }}
            - name: HAZARD_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: HAZARD_SERVICE_URL
            - name: SERVICES_ALLOW_ORIGIN
              value: {{ join "," .Values.cors.origin | quote }}
            - name: SERVICES_ALLOW_METHODS
              value: {{ .Values.cors.methods | quote }}
            - name: SERVICES_ALLOW_HEADERS
              value: {{ .Values.cors.headers | quote }}
            - name: PG_DATABASE
              value: {{ default "nsi" .Values.svc_data.postgresql.database | quote }}
            - name: PG_HOST
              value: {{ default "incore-postgresql-hl" .Values.svc_data.postgresql.host | quote }}
            - name: PG_PORT
              value: {{ default "5432" .Values.svc_data.postgresql.port | quote }}
            - name: PG_USER
              value: {{ default "postgres" .Values.svc_data.postgresql.user | quote }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.existingSecret }}
                  name: {{ .Values.postgresql.existingSecret }}
                  {{- else }}
                  name: {{ include "incore.fullname" . }}-postgresql
                  {{- end }}
                  key: postgresql-password
          ports:
            - containerPort: {{ .Values.svc_data.service.port }}
              name: svc-data
          volumeMounts:
            - name: {{ include "incore.name" . }}-data
              mountPath: /home/incore/data
          livenessProbe:
            httpGet:
              path: /data/api/status
              port: {{ .Values.svc_data.service.port }}
          readinessProbe:
            httpGet:
              path: /data/api/status
              port: {{ .Values.svc_data.service.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: {{ include "incore.name" . }}-data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "incore.name" . }}-data
            {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
