{{- if .Values.svc_plotting.enabled -}}
{{- if not .Values.svc_plotting.persistence.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "incore.name" . }}-plotting
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.svc_plotting.persistence.size | quote }}
  {{- if .Values.svc_plotting.persistence.storageClass }}
  storageClassName: {{ .Values.svc_plotting.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}