apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-auth
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-auth
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-auth
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.auth.image.pullSecrets | default .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: check-url
          image: "ncsa/checks:1.0.0"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: URL
              {{- with first .Values.keycloak.ingress.rules }}
              value: {{ printf "https://%s/auth/realms/%s/" .host $.Values.auth.realm | quote }}
              {{- end }}
      containers:
        - name: auth
          image: "{{ .Values.image.project }}/{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: KEYCLOAK_AUDIENCE
              value: {{ .Values.auth.audience | quote }}
            - name: KEYCLOAK_URL
              {{- with first .Values.keycloak.ingress.rules }}
              value: {{ printf "https://%s/auth/realms/%s/" .host $.Values.auth.realm | quote }}
              {{- end }}
            - name: INFLUXDB_V2_URL
              value: {{ .Values.auth.influxdb.url | quote }}
            - name: INFLUXDB_V2_ORG
              value: {{ .Values.auth.influxdb.org | quote }}
            - name: INFLUXDB_V2_FILE_LOCATION
              value: {{ .Values.auth.influxdb.location | quote }}
            - name: INFLUXDB_V2_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: INFLUXDB_V2_TOKEN
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: { { include "incore.fullname" . } }-services
                  key: COMMON_MONGODB_URI
          volumeMounts:
            - name: {{ include "incore.name" . }}-auth
              mountPath: /srv/incore_auth/data
          ports:
            - containerPort: {{ .Values.auth.service.port }}
              name: auth
          livenessProbe:
            httpGet:
              path: /healthz
              port: auth
          readinessProbe:
            httpGet:
              path: /healthz
              port: auth
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
      volumes:
        - name: {{ include "incore.name" . }}-auth
          persistentVolumeClaim:
            {{- if .Values.auth.persistence.existingClaim }}
            claimName: {{ .Values.auth.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "incore.name" . }}-auth
            {{- end }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
