{{- if .Values.keycloak.realmsecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-realm-secret
  labels:
    {{- include "incore.labels" . | nindent 4 }}
type: generic
data:
  "realm.json": {{ .Files.Get .Values.keycloak.realmsecret | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incore.fullname" . }}-services
  labels:
    {{- include "incore.labels" . | nindent 4 }}
data:
  DATA_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "datadb" | b64enc | quote }}
  DFR3_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "dfr3db" | b64enc | quote }}
  HAZARD_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "hazarddb" | b64enc | quote }}
  SPACE_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "spacedb" | b64enc | quote }}
  SEMANTICS_MONGODB_URI: {{ include "incore.mongodb.uri" . | replace "@DB@" "semanticsdb" | b64enc | quote }}
  DATA_REPO_DATA_DIR: {{ "/home/incore/data/" | b64enc | quote }}
  GEOSERVER_ENABLE: {{ "true" | b64enc | quote }}
  GEOSERVER_PW: {{ "incorerocks" | b64enc | quote }}
  GEOSERVER_URL: {{ "/geoserver/" | b64enc | quote }}
  GEOSERVER_USER: {{ "admin" | b64enc | quote }}
  GEOSERVER_WORKSPACE: {{ "incore" | b64enc | quote }}
  SERVICES_URL: {{ printf "%s-svc-data:%.f" (include "incore.fullname" .) .Values.svc_data.service.port | b64enc | quote }}
