apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-svc-space
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.svc_space.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-svc-space
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-svc-space
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: incore-space-jetty
          image: "{{ .Values.image.project }}/{{ .Values.svc_space.image.repository }}:{{ .Values.svc_space.image.tag }}"
          imagePullPolicy: {{ .Values.svc_space.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: JETTY_PORT
              value: {{ .Values.svc_space.service.port | quote }}
            - name: SERVICES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SERVICES_URL
            - name: DATA_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DATA_SERVICE_URL
            - name: DFR3_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DFR3_SERVICE_URL
            - name: HAZARD_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: HAZARD_SERVICE_URL
            - name: SPACE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SPACE_SERVICE_URL
            - name: SEMANTICS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SEMANTICS_SERVICE_URL
            - name: DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DATA_MONGODB_URI
            - name: DFR3_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: DFR3_MONGODB_URI
            - name: HAZARD_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: HAZARD_MONGODB_URI
            - name: SPACE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SPACE_MONGODB_URI
            - name: SEMANTICS_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: SEMANTICS_MONGODB_URI
            - name: MAESTRO_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: MAESTRO_MONGODB_URI
            - name: COMMON_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: COMMON_MONGODB_URI
            - name: AUTH_LDAP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: AUTH_LDAP_URL
            - name: AUTH_LDAP_USERDN
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: AUTH_LDAP_USERDN
            - name: AUTH_LDAP_ADMINS
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: AUTH_LDAP_ADMINS
            - name: AUTH_LDAP_CACHE_REFRESH_SECS
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: AUTH_LDAP_CACHE_REFRESH_SECS
            - name: AUTH_LDAP_VIEW_ALL
              valueFrom:
                secretKeyRef:
                  name: {{ include "incore.fullname" . }}-services
                  key: AUTH_LDAP_VIEW_ALL
            - name: SERVICES_ALLOW_ORIGIN
              value: {{ join "," .Values.cors.origin | quote }}
            - name: SERVICES_ALLOW_METHODS
              value: {{ .Values.cors.methods | quote }}
            - name: SERVICES_ALLOW_HEADERS
              value: {{ .Values.cors.headers | quote }}
          ports:
            - containerPort: {{ .Values.svc_space.service.port }}
              name: svc-space
          livenessProbe:
            httpGet:
              path: /space/
              port: svc-space
          readinessProbe:
            httpGet:
              path: /space/
              port: svc-space
          resources:
            {{- toYaml .Values.svc_space.resources | nindent 12 }}
      {{- with .Values.svc_space.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.svc_space.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.svc_space.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
